#ROUTING DEL ADMINBUNDLE
MinSalSidPlaAdminBundle_homepage:
    pattern:  /admin/
    defaults: { _controller: MinSalSidPlaAdminBundle:Default:index }

#**************#
#**   ROLES  **#
#**************#
MinSalSidPlaAdminBundle_nuevoRol:
    pattern:  /admin/nuevoRol
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:nuevoRol }
        
MinSalSidPlaAdminBundle_crearRol:
    pattern:  /admin/crearRol
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:addRol }
        
MinSalSidPlaAdminBundle_consultarRoles:
    pattern:  /admin/consultarRoles
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:consultarRoles }
    
MinSalSidPlaAdminBundle_manttRoles:
    pattern:  /admin/manttRoles
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:mattRoles }
    
MinSalSidPlaAdminBundle_manttRolEdicion:
    pattern:  /admin/manttRolEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:manttRolEdicion }
    
MinSalSidPlaAdminBundle_asignarOpcRoles:
    pattern:  /admin/asignarOpcRoles
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:asignarOpcRoles }
    
MinSalSidPlaAdminBundle_opcionesAsignadas:
    pattern:  /admin/opcionesAsignadas
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:opcionesAsignadas }
    
MinSalSidPlaAdminBundle_insertOpcSeleccRol:
    pattern:  /admin/insertOpcSeleccRol    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:insertOpcSeleccRol }

MinSalSidPlaAdminBundle_deleteOpcSeleccRol:
    pattern:  /admin/deleteOpcSeleccRol    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:deleteOpcSeleccRol }
    
MinSalSidPlaAdminBundle_opcionesSinAsignar:
    pattern:  /admin/opcionesSinAsignar    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:opcionesSinAsignar }

MinSalSidPlaAdminBundle_consultarTiposJSONSelect:
    pattern:  /admin/consultarTiposJSONSelect
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:consultarTiposJSONSelect }

MinSalSidPlaAdminBundle_consultarInternoTiposJSONSelect:
    pattern:  /admin/consultarInternoTiposJSONSelect
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:consultarInternoTiposJSONSelect }

#****************#
#*** OPCIONES ***#
#****************#
MinSalSidPlaAdminBundle_crearOpc:
    pattern:  /admin/crearOpc
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:addOcp }
    
MinSalSidPlaAdminBundle_nuevaOpc:
    pattern:  /admin/nuevaOpc
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:nuevaOpc }

MinSalSidPlaAdminBundle_consultarOpciones:
    pattern:  /admin/consultarOpc
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:consultarOpc, _format: json }
    requirements: { _format: (xml|json), _method: GET }  

MinSalSidPlaAdminBundle_mattOpciones:
    pattern:  /admin/mattOpciones
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:mattOpciones }
    
MinSalSidPlaAdminBundle_manttOpcEdicion:
    pattern:  /admin/manttOpcEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:manttOpcEdicion }



MinSalSidPlaAdminBundle_consultarMenCorrtemp:
    pattern:  /admin/consultarMenCorrtemp    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminMenCorreTemp:consultarMenCorrtemp }

MinSalSidPlaAdminBundle_consultarMenCorrtempJSON:
    pattern:  /admin/consultarMenCorrtempJSON    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminMenCorreTemp:consultarMenCorrtempJSON }   
    
MinSalSidPlaAdminBundle_manttMenCorrtempEdicion:
    pattern:  /admin/manttMenCorrtempEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminMenCorreTemp:manttMenCorrtempEdicion }  
    
    
         
MinSalSidPlaAdminBundle_mantenimientoNotificacion:
    pattern:  /admin/mantenimientoNotificacion   
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionNotificacionSistema:mantenimientoNotificacion }
    
MinSalSidPlaAdminBundle_consultarNotificacionJSON:
    pattern:  /admin/consultarNotificacionJSON   
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionNotificacionSistema:consultarNotificacionJSON }
    
MinSalSidPlaAdminBundle_manttNotificacionEdicion:
    pattern:  /admin/manttNotificacionEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionNotificacionSistema:manttNotificacionEdicion }   

#****************************
#*** Empresas o Entidades ***
#****************************
MinSalSidPlaAdminBundle_mantEntidades:
    pattern:  /empresa/mantEntidades
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEntidades:mantEntidades } 
    
MinSalSidPlaAdminBundle_consultarEntidadesJSON:
    pattern:  /empresa/consultarEntidadesJSON
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEntidades:consultarEntidadesJSON } 

MinSalSidPlaAdminBundle_mantEntidadEdicion:
    pattern:  /empresa/mantEntidadEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEntidades:mantEntidadEdicion }

MinSalSidPlaAdminBundle_mantCargarEntidad:
    pattern:  /empresa/mantCargarEntidad/{entId}
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEntidades:mantCargarEntidad } 

#******************
#****  Cuotas   ***
#******************
MinSalSidPlaAdminBundle_mantCargarCuotas:
    pattern:  /empresa/mantCargarCuotas/{entId}/{cuoTipo}
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminCuotas:mantCuotas } 

MinSalSidPlaAdminBundle_mantCuotaEdicion:
    pattern:  /empresa/mantCuotaEdicion/{entId}/{cuoTipo}
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminCuotas:mantCuotaEdicion } 

MinSalSidPlaAdminBundle_consultarCuotasJSON:
    pattern:  /empresa/consultarCuotasJSON/{entId}/{cuoTipo}
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminCuotas:consultarCuotasJSON } 

MinSalSidPlaAdminBundle_consultarAlcoholesJSONSelect:
    pattern:  /empresa/consultarAlcoholesOrgJSONSelect
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminAlcoholes:consultarAlcoholesJSONSelect }

#**********************
#****  LISTADO DNM  ***
#**********************
#listado autorizado
MinSalSidPlaAdminBundle_listadoDNM:
    pattern:  /DNM/listadoDNM
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminListadoDNM:LoadListadoDNM } 
#consulta listado
MinSalSidPlaAdminBundle_ConsultarListadoDNM:
    pattern:  /DNM/ConsultarListadoDNM
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminListadoDNM:ConsultarListadoDNM, _format: json }
    requirements: { _format: (xml|json), _method: GET }  
#manttlistado
MinSalSidPlaAdminBundle_manttListadoDNMEdicion:
    pattern:  /DNM/manttListadoDNMEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminListadoDNM:manttListadoDNMedicion }
    