#ROUTING DEL ADMINBUNDLE
MinSalSidPlaAdminBundle_homepage:
    pattern:  /admin/
    defaults: { _controller: MinSalSidPlaAdminBundle:Default:index }
    
MinSalSidPlaAdminBundle_crearOpc:
    pattern:  /admin/crearOpc
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:addOcp }
    
MinSalSidPlaAdminBundle_nuevaOpc:
    pattern:  /admin/nuevaOpc
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:nuevaOpc }

MinSalSidPlaAdminBundle_nuevoRol:
    pattern:  /admin/nuevoRol
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:nuevoRol }
    
        
MinSalSidPlaAdminBundle_crearRol:
    pattern:  /admin/crearRol
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:addRol }

        
MinSalSidPlaAdminBundle_consultarRoles:
    pattern:  /admin/consultarRoles
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:consultarRoles }
    
MinSalSidPlaAdminBundle_consultarOpciones:
    pattern:  /admin/consultarOpc
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:consultarOpc, _format: json }
    requirements: { _format: (xml|json), _method: GET }  

MinSalSidPlaAdminBundle_manttRoles:
    pattern:  /admin/manttRoles
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:mattRoles }
    
MinSalSidPlaAdminBundle_mattOpciones:
    pattern:  /admin/mattOpciones
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:mattOpciones }
    
MinSalSidPlaAdminBundle_manttOpcEdicion:
    pattern:  /admin/manttOpcEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminOpciones:manttOpcEdicion }
    
MinSalSidPlaAdminBundle_manttRolEdicion:
    pattern:  /admin/manttRolEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:manttRolEdicion }
    
MinSalSidPlaAdminBundle_asignarOpcRoles:
    pattern:  /admin/asignarOpcRoles
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:asignarOpcRoles }
    
MinSalSidPlaAdminBundle_opcionesAsignadas:
    pattern:  /admin/opcionesAsignadas
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:opcionesAsignadas }
    
MinSalSidPlaAdminBundle_insertOpcSeleccRol:
    pattern:  /admin/insertOpcSeleccRol    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:insertOpcSeleccRol }

MinSalSidPlaAdminBundle_deleteOpcSeleccRol:
    pattern:  /admin/deleteOpcSeleccRol    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:deleteOpcSeleccRol }
    
MinSalSidPlaAdminBundle_opcionesSinAsignar:
    pattern:  /admin/opcionesSinAsignar    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminRoles:opcionesSinAsignar }

MinSalSidPlaAdminBundle_consultarUnidadesOrg:
    pattern:  /admin/consultarUnidadesOrg    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminUnidadOrg:consultarUnidadesOrg }

MinSalSidPlaAdminBundle_ingresoNuevaUnidadesOrg:
    pattern:  /admin/ingresoNuevaUnidadesOrg    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminUnidadOrg:ingresoNuevaUnidadesOrg }
    
MinSalSidPlaAdminBundle_ingresarUnidadOrg:
    pattern:  /admin/ingresarUnidadOrg    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminUnidadOrg:ingresarUnidadOrg }  
    
MinSalSidPlaAdminBundle_consultarMunicipiosJSON:
    pattern:  /admin/consultarMunicipiosJSON    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminUnidadOrg:consultarMunicipiosJSON } 
    
MinSalSidPlaAdminBundle_consultarUnidadesOrgJSON:
    pattern:  /admin/consultarUnidadesOrgJSON    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminUnidadOrg:consultarUnidadesOrgJSON }    

MinSalSidPlaAdminBundle_consultarMenCorrtemp:
    pattern:  /admin/consultarMenCorrtemp    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminMenCorreTemp:consultarMenCorrtemp }

MinSalSidPlaAdminBundle_consultarMenCorrtempJSON:
    pattern:  /admin/consultarMenCorrtempJSON    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminMenCorreTemp:consultarMenCorrtempJSON }   
    
MinSalSidPlaAdminBundle_manttMenCorrtempEdicion:
    pattern:  /admin/manttMenCorrtempEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminMenCorreTemp:manttMenCorrtempEdicion }  
         
MinSalSidPlaAdminBundle_mantenimientoNotificacion:
    pattern:  /admin/mantenimientoNotificacion   
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionNotificacionSistema:mantenimientoNotificacion }
    
MinSalSidPlaAdminBundle_consultarNotificacionJSON:
    pattern:  /admin/consultarNotificacionJSON   
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionNotificacionSistema:consultarNotificacionJSON }
    
MinSalSidPlaAdminBundle_manttNotificacionEdicion:
    pattern:  /admin/manttNotificacionEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionNotificacionSistema:manttNotificacionEdicion }   
  
MinSalSidPlaAdminBundle_mattUnidadesOrg:
    pattern:  /admin/mattUnidadesOrg
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminUnidadOrg:mattUnidadesOrg }
    
MinSalSidPlaAdminBundle_mattEmpleados:
    pattern:  /admin/mattEmpleados
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEmpleados:mattEmpleados } 
    
MinSalSidPlaAdminBundle_consultarEmpleadosJSON:
    pattern:  /admin/consultarEmpleadosJSON
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEmpleados:consultarEmpleadosJSON } 

MinSalSidPlaAdminBundle_manttEmpleadoEdicion:
    pattern:  /admin/manttEmpleadoEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEmpleados:manttEmpleadoEdicion } 

MinSalSidPlaAdminBundle_consultarUnidadesOrgJSONSelect:
    pattern:  /admin/consultarUnidadesOrgJSONSelect
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminUnidadOrg:consultarUnidadesOrgJSONSelect } 
    
MinSalSidPlaAdminBundle_editarUnidadesOrg:
    pattern:  /admin/editarUnidadesOrg    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminUnidadOrg:editarUnidadesOrg }  
    
MinSalSidPlaAdminBundle_editandoUnidadesOrg:
    pattern:  /admin/editandoUnidadesOrg    
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminUnidadOrg:editandoUnidadesOrg }  

#****************************
#*** Empresas o Entidades ***
#****************************
MinSalSidPlaAdminBundle_mantEntidades:
    pattern:  /empresa/mantEntidades
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEntidades:mantEntidades } 
    
#listado autorizado
MinSalSidPlaAdminBundle_listadoDNM:
    pattern:  /admin/listadoDNM
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminListadoDNM:LoadListadoDNM } 
#consulta listado
MinSalSidPlaAdminBundle_ConsultarListadoDNM:
    pattern:  /admin/ConsultarListadoDNM
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminListadoDNM:ConsultarListadoDNM, _format: json }
    requirements: { _format: (xml|json), _method: GET }  
#manttlistado
MinSalSidPlaAdminBundle_manttListadoDNMEdicion:
    pattern:  /admin/manttListadoDNMEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminListadoDNM:manttListadoDNMedicion }
    
MinSalSidPlaAdminBundle_consultarEntidadesJSON:
    pattern:  /empresa/consultarEntidadesJSON
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEntidades:consultarEntidadesJSON } 

MinSalSidPlaAdminBundle_mantEntidadEdicion:
    pattern:  /empresa/mantEntidadEdicion
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEntidades:mantEntidadEdicion }

MinSalSidPlaAdminBundle_mantCargarEntidad:
    pattern:  /empresa/mantCargarEntidad/{entId}
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminEntidades:mantCargarEntidad } 

#******************
#****  Cuotas   ***
#******************
MinSalSidPlaAdminBundle_mantCargarCuotas:
    pattern:  /empresa/mantCargarCuotas/{entId}/{cuoTipo}
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminCuotas:mantCuotas } 

MinSalSidPlaAdminBundle_mantCuotaEdicion:
    pattern:  /empresa/mantCuotaEdicion/{entId}/{cuoTipo}
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminCuotas:mantCuotaEdicion } 

MinSalSidPlaAdminBundle_consultarCuotasJSON:
    pattern:  /empresa/consultarCuotasJSON/{entId}/{cuoTipo}
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminCuotas:consultarCuotasJSON } 

MinSalSidPlaAdminBundle_consultarAlcoholesJSONSelect:
    pattern:  /empresa/consultarAlcoholesOrgJSONSelect
    defaults: { _controller: MinSalSidPlaAdminBundle:AccionAdminAlcoholes:consultarAlcoholesJSONSelect }
