<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MinSalSidPlaAdminBundleEntityUnidadOrganizativaProxy extends \MinSal\SidPla\AdminBundle\Entity\UnidadOrganizativa implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getSubUnidades()
    {
        $this->__load();
        return parent::getSubUnidades();
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setParent($parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getIdUnidadOrg()
    {
        $this->__load();
        return parent::getIdUnidadOrg();
    }

    public function getNombreUnidad()
    {
        $this->__load();
        return parent::getNombreUnidad();
    }

    public function setNombreUnidad($nombreUnidad)
    {
        $this->__load();
        return parent::setNombreUnidad($nombreUnidad);
    }

    public function getDescripcionUnidad()
    {
        $this->__load();
        return parent::getDescripcionUnidad();
    }

    public function setDescripcionUnidad($descripcionUnidad)
    {
        $this->__load();
        return parent::setDescripcionUnidad($descripcionUnidad);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function addUnidadOrganizativa(\MinSal\SidPla\AdminBundle\Entity\UnidadOrganizativa $subUnidades)
    {
        $this->__load();
        return parent::addUnidadOrganizativa($subUnidades);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idUnidadOrg', 'nombreUnidad', 'descripcionUnidad', 'subUnidades', 'parent');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}