#src/MinSal/SCA/DependenciaBundle/Resources/config/rounting.yml
MinSalSCADependenciaBundle_homepage:
    pattern:  /Dependencia
    defaults: { _controller: MinSalSCADependenciaBundle:Default:index }
