imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        port:     %database_port%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: %mailer_encryption%
    auth_mode: %mailer_auth_mode%
    port:      %mailer_port%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

#para seguridad 
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: MinSal\SCA\UsersBundle\Entity\User
    from_email:
        address: noreply@sca.gob.sv
        sender_name: SCA
    registration:
        form:
            type: sca_user_registration
            handler: sca_user.form.handler.registration
        confirmation:
            enabled: false
            from_email:
                address: registration@sca.gob.sv
                sender_name: SCA Registro Usuario
            template: MinSalSCAUsersBundle:Registration\Email:register.email.twig
    change_password:
        form:
            type: sca_change_password
            #handler:  sca_user.form.handler.changePassword
    resetting:
        email:
            template: MinSalSCAUsersBundle:Resetting\Email:resetting.email.twig
            from_email:
                address:  reset@sca.gob.sv
                sender_name: SCA Restauración Clave
    service: 
        mailer: fos_user.mailer.default    #twig_swift