<?php
use Doctrine\Common\Annotations\AnnotationRegistry;
// autoload.php generated by Composer

require_once __DIR__ . '/../vendor/composer' . '/autoload_real.php';

$loader = ComposerAutoloaderInitbcd784c99131628f08c7391b74add7f8::getLoader();


AnnotationRegistry::registerFile(__DIR__.'/../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php');
/*
$loader->registerPrefixes(array(
    'Twig_Extensions_' => __DIR__.'/../vendor/twig/extensions/lib',
    'Twig_'            => __DIR__.'/../vendor/twig/twig/lib',
));/**/

AnnotationRegistry::registerLoader(function($class) use ($loader) {
    $loader->loadClass($class);
    return class_exists($class, false);
});/**/

return $loader;