<?php
use Doctrine\Common\Annotations\AnnotationRegistry;
// autoload.php generated by Composer

require_once __DIR__ . '/../vendor/composer' . '/autoload_real.php';

$loader = ComposerAutoloaderInitd8fdc171dd83ece79535701487795852::getLoader();

if (!function_exists('intl_get_error_code')) {
    require_once __DIR__.'/../vendor/symfony/symfony/src/Symfony/Component/Locale/Resources/stubs/functions.php';

    $loader->add('', __DIR__.'/../vendor/symfony/symfony/src/Symfony/Component/Locale/Resources/stubs');
}

AnnotationRegistry::registerFile(__DIR__.'/../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php');
/*
$loader->registerPrefixes(array(
    'Twig_Extensions_' => __DIR__.'/../vendor/twig/extensions/lib',
    'Twig_'            => __DIR__.'/../vendor/twig/twig/lib',
));/**/

/*AnnotationRegistry::registerLoader(function($class) use ($loader) {
    $loader->loadClass($class);
    return class_exists($class, false);
});/**/

AnnotationRegistry::registerLoader(array($loader, 'loadClass'));

return $loader;