parameters:
#    min_sal_sid_pla_sca_procesos.example.class: MinSal\SCA\ProcesosBundle\Example

services:
#    min_sal_sid_pla_sca_procesos.example:
#        class: %min_sal_sid_pla_sca_procesos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
