<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MinSalSidPlaAdminBundleEntityDepartamentoPaisProxy extends \MinSal\SidPla\AdminBundle\Entity\DepartamentoPais implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setIdDepto($idDepto)
    {
        $this->__load();
        return parent::setIdDepto($idDepto);
    }

    public function getIdDepto()
    {
        $this->__load();
        return parent::getIdDepto();
    }

    public function setNombreDepto($nombreDepto)
    {
        $this->__load();
        return parent::setNombreDepto($nombreDepto);
    }

    public function getNombreDepto()
    {
        $this->__load();
        return parent::getNombreDepto();
    }

    public function addMunicipios(\MinSal\SidPla\AdminBundle\Entity\Municipio $municipios)
    {
        $this->__load();
        return parent::addMunicipios($municipios);
    }

    public function getMunicipios()
    {
        $this->__load();
        return parent::getMunicipios();
    }

    public function addMunicipio(\MinSal\SidPla\AdminBundle\Entity\Municipio $municipios)
    {
        $this->__load();
        return parent::addMunicipio($municipios);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idDepto', 'nombreDepto', 'municipios');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}