<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MinSalSidPlaAdminBundleEntityMensajeCorreTempProxy extends \MinSal\SidPla\AdminBundle\Entity\MensajeCorreTemp implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getMencortemCodigo()
    {
        $this->__load();
        return parent::getMencortemCodigo();
    }

    public function setMencortemTexto($mencortemTexto)
    {
        $this->__load();
        return parent::setMencortemTexto($mencortemTexto);
    }

    public function getMencortemTexto()
    {
        $this->__load();
        return parent::getMencortemTexto();
    }

    public function setMencortemNombre($mencortemNombre)
    {
        $this->__load();
        return parent::setMencortemNombre($mencortemNombre);
    }

    public function getMencortemNombre()
    {
        $this->__load();
        return parent::getMencortemNombre();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'mencortem_codigo', 'mencortem_texto', 'mencortem_nombre');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}