<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MinSalSidPlaAdminBundleEntityOpcionSistemaProxy extends \MinSal\SidPla\AdminBundle\Entity\OpcionSistema implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getIdOpcionSistema()
    {
        $this->__load();
        return parent::getIdOpcionSistema();
    }

    public function setNombreOpcion($nombreOpcion)
    {
        $this->__load();
        return parent::setNombreOpcion($nombreOpcion);
    }

    public function getNombreOpcion()
    {
        $this->__load();
        return parent::getNombreOpcion();
    }

    public function setDescripcionOpcion($descripcionOpcion)
    {
        $this->__load();
        return parent::setDescripcionOpcion($descripcionOpcion);
    }

    public function getDescripcionOpcion()
    {
        $this->__load();
        return parent::getDescripcionOpcion();
    }

    public function setEnlace($enlace)
    {
        $this->__load();
        return parent::setEnlace($enlace);
    }

    public function getEnlace()
    {
        $this->__load();
        return parent::getEnlace();
    }

    public function setIdOpcionSistema2($idOpcionSistema2)
    {
        $this->__load();
        return parent::setIdOpcionSistema2($idOpcionSistema2);
    }

    public function getIdOpcionSistema2()
    {
        $this->__load();
        return parent::getIdOpcionSistema2();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idOpcionSistema', 'nombreOpcion', 'descripcionOpcion', 'enlace', 'idOpcionSistema2');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}