<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MinSalSidPlaAdminBundleEntityInformacionGeneralProxy extends \MinSal\SidPla\AdminBundle\Entity\InformacionGeneral implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setIdInformacionGeneral($idInformacionGeneral)
    {
        $this->__load();
        return parent::setIdInformacionGeneral($idInformacionGeneral);
    }

    public function getIdInformacionGeneral()
    {
        $this->__load();
        return parent::getIdInformacionGeneral();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setFax($fax)
    {
        $this->__load();
        return parent::setFax($fax);
    }

    public function getFax()
    {
        $this->__load();
        return parent::getFax();
    }

    public function setFechaActualizacion($fechaActualizacion)
    {
        $this->__load();
        return parent::setFechaActualizacion($fechaActualizacion);
    }

    public function getFechaActualizacion()
    {
        $this->__load();
        return parent::getFechaActualizacion();
    }

    public function setDireccion($direccion)
    {
        $this->__load();
        return parent::setDireccion($direccion);
    }

    public function getDireccion()
    {
        $this->__load();
        return parent::getDireccion();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setUnidadOrganizativa(\MinSal\SidPla\AdminBundle\Entity\UnidadOrganizativa $unidadOrganizativa)
    {
        $this->__load();
        return parent::setUnidadOrganizativa($unidadOrganizativa);
    }

    public function getUnidadOrganizativa()
    {
        $this->__load();
        return parent::getUnidadOrganizativa();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idInformacionGeneral', 'telefono', 'fax', 'fechaActualizacion', 'direccion', 'email', 'unidadOrganizativa');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}