<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MinSalSidPlaAdminBundleEntityRolSistemaProxy extends \MinSal\SidPla\AdminBundle\Entity\RolSistema implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getIdRol()
    {
        $this->__load();
        return parent::getIdRol();
    }

    public function setNombreRol($nombreRol)
    {
        $this->__load();
        return parent::setNombreRol($nombreRol);
    }

    public function setIdRol($idRol)
    {
        $this->__load();
        return parent::setIdRol($idRol);
    }

    public function getNombreRol()
    {
        $this->__load();
        return parent::getNombreRol();
    }

    public function setFuncionesRol($funcionesRol)
    {
        $this->__load();
        return parent::setFuncionesRol($funcionesRol);
    }

    public function getFuncionesRol()
    {
        $this->__load();
        return parent::getFuncionesRol();
    }

    public function addUsuarios(\MinSal\SidPla\UsersBundle\Entity\User $usuarios)
    {
        $this->__load();
        return parent::addUsuarios($usuarios);
    }

    public function getUsuarios()
    {
        $this->__load();
        return parent::getUsuarios();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function addOpcionesSistema(\MinSal\SidPla\AdminBundle\Entity\OpcionSistema $opcionesSistema)
    {
        $this->__load();
        return parent::addOpcionesSistema($opcionesSistema);
    }

    public function getOpcionesSistema()
    {
        $this->__load();
        return parent::getOpcionesSistema();
    }

    public function addUser(\MinSal\SidPla\UsersBundle\Entity\User $usuarios)
    {
        $this->__load();
        return parent::addUser($usuarios);
    }

    public function addOpcionSistema(\MinSal\SidPla\AdminBundle\Entity\OpcionSistema $opcionesSistema)
    {
        $this->__load();
        return parent::addOpcionSistema($opcionesSistema);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idRol', 'nombreRol', 'funcionesRol', 'usuarios', 'opcionesSistema');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}