<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MinSalSidPlaAdminBundleEntityEntidadProxy extends \MinSal\SidPla\AdminBundle\Entity\Entidad implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setUsuario(\MinSal\SidPla\UsersBundle\Entity\User $usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function getEntId()
    {
        $this->__load();
        return parent::getEntId();
    }

    public function setEntId($entId)
    {
        $this->__load();
        return parent::setEntId($entId);
    }

    public function getEntRegDgii()
    {
        $this->__load();
        return parent::getEntRegDgii();
    }

    public function setEntRegDgii($entRegDgii)
    {
        $this->__load();
        return parent::setEntRegDgii($entRegDgii);
    }

    public function getEntRegMinsal()
    {
        $this->__load();
        return parent::getEntRegMinsal();
    }

    public function setEntRegMinsal($entRegMinsal)
    {
        $this->__load();
        return parent::setEntRegMinsal($entRegMinsal);
    }

    public function getEntNrc()
    {
        $this->__load();
        return parent::getEntNrc();
    }

    public function setEntNrc($entNrc)
    {
        $this->__load();
        return parent::setEntNrc($entNrc);
    }

    public function getEntTel()
    {
        $this->__load();
        return parent::getEntTel();
    }

    public function setEntTel($entTel)
    {
        $this->__load();
        return parent::setEntTel($entTel);
    }

    public function getEntGiro()
    {
        $this->__load();
        return parent::getEntGiro();
    }

    public function setEntGiro($entGiro)
    {
        $this->__load();
        return parent::setEntGiro($entGiro);
    }

    public function getEntTipoPersona()
    {
        $this->__load();
        return parent::getEntTipoPersona();
    }

    public function setEntTipoPersona($entTipoPersona)
    {
        $this->__load();
        return parent::setEntTipoPersona($entTipoPersona);
    }

    public function getEntEmail()
    {
        $this->__load();
        return parent::getEntEmail();
    }

    public function setEntEmail($entEmail)
    {
        $this->__load();
        return parent::setEntEmail($entEmail);
    }

    public function getEntNit()
    {
        $this->__load();
        return parent::getEntNit();
    }

    public function setEntNit($entNit)
    {
        $this->__load();
        return parent::setEntNit($entNit);
    }

    public function getEntNombre()
    {
        $this->__load();
        return parent::getEntNombre();
    }

    public function setEntNombre($entNombre)
    {
        $this->__load();
        return parent::setEntNombre($entNombre);
    }

    public function getEntNombComercial()
    {
        $this->__load();
        return parent::getEntNombComercial();
    }

    public function setEntNombComercial($entNombComercial)
    {
        $this->__load();
        return parent::setEntNombComercial($entNombComercial);
    }

    public function getEntTipoDoc()
    {
        $this->__load();
        return parent::getEntTipoDoc();
    }

    public function setEntTipoDoc($entTipoDoc)
    {
        $this->__load();
        return parent::setEntTipoDoc($entTipoDoc);
    }

    public function getEntActua()
    {
        $this->__load();
        return parent::getEntActua();
    }

    public function setEntActua($entActua)
    {
        $this->__load();
        return parent::setEntActua($entActua);
    }

    public function getEntRepNit()
    {
        $this->__load();
        return parent::getEntRepNit();
    }

    public function setEntRepNit($entRepNit)
    {
        $this->__load();
        return parent::setEntRepNit($entRepNit);
    }

    public function getEntRepDoc()
    {
        $this->__load();
        return parent::getEntRepDoc();
    }

    public function setEntRepDoc($entRepDoc)
    {
        $this->__load();
        return parent::setEntRepDoc($entRepDoc);
    }

    public function getEntRepNombre()
    {
        $this->__load();
        return parent::getEntRepNombre();
    }

    public function setEntRepNombre($entRepNombre)
    {
        $this->__load();
        return parent::setEntRepNombre($entRepNombre);
    }

    public function getEntDireccionMatriz()
    {
        $this->__load();
        return parent::getEntDireccionMatriz();
    }

    public function setEntDireccionMatriz($entDireccionMatriz)
    {
        $this->__load();
        return parent::setEntDireccionMatriz($entDireccionMatriz);
    }

    public function getEntUsosAlcohol()
    {
        $this->__load();
        return parent::getEntUsosAlcohol();
    }

    public function setEntUsosAlcohol($entUsosAlcohol)
    {
        $this->__load();
        return parent::setEntUsosAlcohol($entUsosAlcohol);
    }

    public function getEntYear()
    {
        $this->__load();
        return parent::getEntYear();
    }

    public function setEntYear($entYear)
    {
        $this->__load();
        return parent::setEntYear($entYear);
    }

    public function getEntVenc()
    {
        $this->__load();
        return parent::getEntVenc();
    }

    public function setEntVenc($entVenc)
    {
        $this->__load();
        return parent::setEntVenc($entVenc);
    }

    public function getEntDistribuidor()
    {
        $this->__load();
        return parent::getEntDistribuidor();
    }

    public function setEntDistribuidor($entDistribuidor)
    {
        $this->__load();
        return parent::setEntDistribuidor($entDistribuidor);
    }

    public function getEntProductor()
    {
        $this->__load();
        return parent::getEntProductor();
    }

    public function setEntProductor($entProductor)
    {
        $this->__load();
        return parent::setEntProductor($entProductor);
    }

    public function getEntComprador()
    {
        $this->__load();
        return parent::getEntComprador();
    }

    public function setEntComprador($entComprador)
    {
        $this->__load();
        return parent::setEntComprador($entComprador);
    }

    public function getEntCompVend()
    {
        $this->__load();
        return parent::getEntCompVend();
    }

    public function setEntCompVend($entCompVend)
    {
        $this->__load();
        return parent::setEntCompVend($entCompVend);
    }

    public function getEntProdEstEtil()
    {
        $this->__load();
        return parent::getEntProdEstEtil();
    }

    public function setEntProdEstEtil($entProdEstEtil)
    {
        $this->__load();
        return parent::setEntProdEstEtil($entProdEstEtil);
    }

    public function getEntHabilitado()
    {
        $this->__load();
        return parent::getEntHabilitado();
    }

    public function setEntHabilitado($entHabilitado)
    {
        $this->__load();
        return parent::setEntHabilitado($entHabilitado);
    }

    public function getEntComentario()
    {
        $this->__load();
        return parent::getEntComentario();
    }

    public function setEntComentario($entComentario)
    {
        $this->__load();
        return parent::setEntComentario($entComentario);
    }

    public function getAuditDateIns()
    {
        $this->__load();
        return parent::getAuditDateIns();
    }

    public function setAuditDateIns($auditDateIns)
    {
        $this->__load();
        return parent::setAuditDateIns($auditDateIns);
    }

    public function getAuditUserIns()
    {
        $this->__load();
        return parent::getAuditUserIns();
    }

    public function setAuditUserIns($auditUserIns)
    {
        $this->__load();
        return parent::setAuditUserIns($auditUserIns);
    }

    public function getAuditDateUpd()
    {
        $this->__load();
        return parent::getAuditDateUpd();
    }

    public function setAuditDateUpd($auditDateUpd)
    {
        $this->__load();
        return parent::setAuditDateUpd($auditDateUpd);
    }

    public function getAuditUserUpd()
    {
        $this->__load();
        return parent::getAuditUserUpd();
    }

    public function setAuditUserUpd($auditUserUpd)
    {
        $this->__load();
        return parent::setAuditUserUpd($auditUserUpd);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'entId', 'entRegDgii', 'entRegMinsal', 'entNrc', 'entTel', 'entGiro', 'entTipoPersona', 'entEmail', 'entNit', 'entNombre', 'entNombComercial', 'entTipoDoc', 'entActua', 'entRepNit', 'entRepDoc', 'entRepNombre', 'entDireccionMatriz', 'entUsosAlcohol', 'entYear', 'entVenc', 'entDistribuidor', 'entProductor', 'entComprador', 'entCompVend', 'entProdEstEtil', 'entHabilitado', 'entComentario', 'auditDateIns', 'auditUserIns', 'auditDateUpd', 'auditUserUpd', 'users');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}